name: Build Godot Project With Latest Codes

on:
  release: {}

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [Linux, Windows Desktop, macOS, Android]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build
        id: build
        uses: manleydev/build-godot-action@master
        with:
          name: example
          preset: ${{ matrix.platform }}
          debugMode: "false"
          name: "Baldi's Basics In Education And Learning"
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Client - ${{ matrix.platform }}
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}
