name: Build Godot Project With Latest Codes

on:
  push: {}
  pull_request: {}

jobs:
  Godot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Get tag or commit id
        id: get-version-id
        uses: iawia002/get-tag-or-commit-id@v1
        with:
          length: 7
      - name: Check commit ids and some android works
        run: |
          echo "COMMIT ID:" ${{steps.get-version-id.outputs.id}}
          export GODOT_ANDROID_KEYSTORE_DEBUG_PATH=.\debug.keystore
          export GODOT_ANDROID_KEYSTORE_DEBUG_USER=root
          export GODOT_ANDROID_KEYSTORE_DEBUG_PASSWORD=123456
          export GODOT_ANDROID_KEYSTORE_RELEASE_PATH=.\release.keystore
          export GODOT_ANDROID_KEYSTORE_RELEASE_USER=root
          export GODOT_ANDROID_KEYSTORE_RELEASE_PASSWORD=123456
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Set Project Name
        run: |
          sed -i "s/Baldi godot remake/Baldi's Basics In Education And Learning - build ${{steps.get-version-id.outputs.id}}/g" project.godot
          sed -i "s/0.0.0.0/${{steps.get-version-id.outputs.id}}/g" project.godot
      - name: export game
        id: export
        uses: firebelley/godot-export@v6.0.0
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.3/Godot_v4.3-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.3/Godot_v4.3-stable_export_templates.tpz
          relative_project_path: ./
          export_debug: true
      - name: Upload Artifact For Linux
        uses: actions/upload-artifact@v3
        with:
          name: Linux - build ${{steps.get-version-id.outputs.id}}
          path: /home/runner/.local/share/godot/builds/Linux/linux.x86_64
      - name: Upload Artifact For MacOS
        uses: actions/upload-artifact@v3
        with:
          name: MacOS - build ${{steps.get-version-id.outputs.id}}
          path: /home/runner/.local/share/godot/builds/macOS/mac.zip
      - name: Upload Artifact For Windows
        uses: actions/upload-artifact@v3
        with:
          name: Windows - build ${{steps.get-version-id.outputs.id}}
          path: /home/runner/.local/share/godot/builds/Windows Desktop/win.exe
      - name: Upload Artifact For Android
        uses: actions/upload-artifact@v3
        with:
          name: Android - build ${{steps.get-version-id.outputs.id}}
          path: /home/runner/.local/share/godot/builds/Android/android.apk
