name: Build Godot Project For Releases

on:
  release:
    types: [published]

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [Linux, Windows Desktop, macOS, Android]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build
        id: build
        uses: manleydev/build-godot-action@master
        with:
          preset: ${{ matrix.platform }}
          debugMode: "false"
          name: "Baldi's Basics In Education And Learning - v ${{github.event.release.name}}"
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform }} - ${{github.event.release.name}}
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}
