name: Build Godot Project With Latest Codes

on:
  push: {}
  pull_request: {}

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [Linux, Windows Desktop, macOS, Android]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Get tag or commit id
        id: get-version-id
        uses: iawia002/get-tag-or-commit-id@v1
        with:
          length: 7
      - name: Check commit ids
        run: |
          echo "COMMIT ID:" ${{steps.get-version-id.outputs.id}}
      - name: Build
        id: build
        uses: manleydev/build-godot-action@master
        with:
          preset: ${{ matrix.platform }}
          debugMode: "true"
          name: "Baldi's Basics In Education And Learning - build ${{steps.get-version-id.outputs.id}}"
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform }} - ${{steps.get-version-id.outputs.id}}
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}
