name: Build Godot Project With Latest Codes

on:
  push: {}
  pull_request: {}

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [Linux, Windows Desktop, macOS, Android]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: fufuhu/get-commit-id@main
        with:
          path: ./
      - name: Build
        id: build
        uses: manleydev/build-godot-action@master
        with:
          preset: ${{ matrix.platform }}
          debugMode: "true"
          name: "Baldi's Basics In Education And Learning - build ${{ steps.get_commit_id.outputs.commit_id }}"
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Client - ${{ matrix.platform }}
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}
